/**
 * TelephonyProvider — adapter contract for any telephony backend.
 *
 * Implementations: MockTelephonyProvider (default), TwilioProvider (TODO),
 * AfricasTalkingProvider (TODO), SipProvider (TODO).
 *
 * Provider emits events through `onCallEvent`; the gateway forwards them
 * to the softphone Socket.IO namespace.
 */
import { CallStatus, CallDirection, LanguagePreference } from '@teletrade/shared';

export type ProviderCallEvent =
  | { type: 'inbound.queued'; callId: string; fromNumber: string; language?: LanguagePreference; productMenu?: string }
  | { type: 'ringing'; callId: string }
  | { type: 'answered'; callId: string; agentId: string }
  | { type: 'hangup'; callId: string; reason?: string }
  | { type: 'missed'; callId: string }
  | { type: 'dropped'; callId: string; reason: string };

export interface DialOptions {
  toNumber: string;
  agentId: string;
  callId: string; // pre-generated by our system so we can correlate
  metadata?: Record<string, unknown>;
}

export interface SimulateInboundOptions {
  fromNumber: string;
  language?: LanguagePreference;
  productMenu?: string;
}

export interface TelephonyProvider {
  readonly name: string;

  dial(options: DialOptions): Promise<{ externalCallId: string; status: CallStatus }>;

  hangup(callId: string): Promise<void>;

  answer(callId: string, agentId: string): Promise<void>;

  /** Used in dev — simulates an inbound call hitting the IVR. */
  simulateInbound(opts: SimulateInboundOptions): Promise<{
    callId: string;
    direction: CallDirection;
    status: CallStatus;
  }>;

  onCallEvent(handler: (evt: ProviderCallEvent) => void): void;
}
